### PR TITLE
Update bcm/config.bcm file for EC SAI on MV2 TD3 TH3 HX5

### PR DESCRIPTION
**Pull request by peter-yu**
#### Why I did it
Update the bcm configuration file for EC SAI
#### How I did it
1. The file to be used with ecSAI will be named as 'xxx_ec.bcm' or 'xxx_ec.config.bcm'
2. Accton-AS4630-54NPE didn't support community SAI.  Update the bcm file directly.

#### How to verify it
N/A
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

### CODE REVIEW

**Comment by peter-yu** [comment]
@gord1306 @linarnan @chenkelly  Please help to review

**Comment by gord1306** [comment]
@peter-yu , please also update the Accton-AS9716-32D/th3-as9716-32x400G.config.bcm

**Comment by peter-yu** [comment]
Note: This requires build script to replace xxx_ec.bcm to xxx.bcm

**Comment by peter-yu** [comment]
@gord1306 Please help to review

**Comment by peter-yu** [comment]
@gord1306 Please help to review

**Pull request merged**
